### ISSUE TITLE
Unable to find package Naxma.LibPhoneNumber.Droid

### ISSUE THREAD

**Issue by jesulink2514** [NAXAM/accountkit-android-binding#1]
Install-Package : Unable to find package Naxma.LibPhoneNumber.Droid. No packages exist with this id in source(s): Nuget
At line:1 char:1
+ Install-Package Naxam.AccountKit.Droid -IgnoreDependencies
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by tuyen-vuduc** [comment]
A typo mistake. I will fix it soon.

**Comment by tuyen-vuduc** [comment]
@jesulink2514 Plz check out the latest version will be rolled out in couple of minutes.
