### ISSUE TITLE
Need help in AccountKit.GetCurrentAccount

### ISSUE THREAD

**Issue by sureshraji1986** [NAXAM/accountkit-android-binding#4]
Hi,

Thank you for your team for the wonderful work. I have successfully tested account kit in xamarin android. 

but I want to read Account.PhoneNumber after successful verification

Could you please help me how to use this part in C#

AccountKit.getCurrentAccount(new AccountKitCallback<Account>() {
  @Override
  public void onSuccess(final Account account) {
    // Get Account Kit ID
    String accountKitId = account.getId();

    // Get phone number
    PhoneNumber phoneNumber = account.getPhoneNumber();
    if (phoneNumber != null) {
      String phoneNumberString = phoneNumber.toString();
    }

    // Get email
    String email = account.getEmail();
  }
  
  @Override
  public void onError(final AccountKitError error) {
    // Handle Error
  }
});

**Comment by tuyen-vuduc** [comment]
Hey, have you read the sample code?

Anyway, the API are similar between C# and Java. You should learn those yourself, don't ask for this simple question.

Cheers.
